#estagio 1 - base
FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS base
RUN mkdir /app
WORKDIR /app
ENV ASPNETCORE_URLS=http://+:80
EXPOSE 80/tcp

#estagio 2 - publish
FROM mcr.microsoft.com/dotnet/sdk:5.0 AS publish
WORKDIR /app
COPY mvc1.csproj .
RUN dotnet restore
COPY . .
RUN dotnet publish -c Release -o dist

#estgio 3 - final
FROM base AS final
WORKDIR /dist
COPY --from=publish /app/dist .
ENTRYPOINT ["dotnet","mvc1.dll"]